In [20]:
import numpy as np

In [70]:
def solve(A, b, max_n_iters, tol):
    it = 1
    n = A.shape[0]
    xk = np.zeros(n)
    grads = np.array([])

    while np.linalg.norm(A @ xk - b) > tol and it < max_n_iters:
        grad = A @ xk - b
        grads = np.append(grads, grad)
#         step = np.dot(grad, grad) / np.dot((A @ grad), grad)
        step = 0.1
        xk = xk - step * grad
        it += 1
        print(f'x = {xk}')
        print(f'grad = {grad}')
        print(f'step = {step}')
        print()
        print()
        print()

    return xk, grads


# def Print(Q, R, S, real_solution):
#     print(f"Q = \n{Q},\n R = \n{R},\n solution = {S},\nreal solution = \n{real_solution}\n\n\n")





In [71]:
if __name__ == '__main__':

    A = np.array([
            [1/17, 1/51, 1/51],
            [1/17, -5/51, 10/51],
            [-4/17, 1/51, -20/51]
    ])
    b = np.array([20, 100, 1000])

    tol = 0.0001
    max_n_iter = 1000

    real_solution = np.linalg.solve(A, b)
    print(real_solution)
    sol, grads = solve(A, b, max_n_iter, tol)

    print(sol)
    print()
    print(grads)

[  6300. -11000.  -6880.]
x = [  2.  10. 100.]
grad = [  -20.  -100. -1000.]
step = 0.1



x = [  3.77254902  18.1254902  203.94901961]
grad = [  -17.7254902    -81.25490196 -1039.49019608]
step = 0.1



x = [  5.31491734  24.28199923 312.00024606]
grad = [  -15.4236832    -61.56509035 -1080.51226451]
step = 0.1



x = [  6.62427617  28.37114194 424.31299494]
grad = [  -13.09358829   -40.89142713 -1123.12748882]
step = 0.1



x = [  7.69769388  30.29046142 541.05295586]
grad = [  -10.73417715   -19.19319474 -1167.39960923]
step = 0.1



x = [  8.53213212  29.93326469 662.39244799]
grad = [   -8.34438237     3.57196732 -1213.39492123]
step = 0.1



x = [  9.12444171  27.18845184 788.51068579]
grad = [   -5.9230959     27.44812849 -1261.18237805]
step = 0.1



x = [  9.47135845  21.94033826 919.59405553]
grad = [   -3.4691674     52.48113576 -1310.83369734]
step = 0.1



x = [   9.56949871   14.06846975 1055.83640273]
grad = [-9.81402566e-01  7.87186851e+01 -1.36242347e+03]
step = 0.1




x = [  -961277.60195404 -40391481.04714219  62834047.31487032]
grad = [   368717.1391219   15597752.6787892  -24235297.76264467]
step = 0.1



x = [  -999626.0597224  -42013851.52866877  65354808.28765679]
grad = [   383484.57768365  16223704.81526573 -25207609.72786471]
step = 0.1



x = [ -1039510.48831028 -43701328.70972905  67976701.43386294]
grad = [   398844.28587884  16874771.81060283 -26218931.46206148]
step = 0.1



x = [ -1080992.49077931 -45456524.83996894  70703784.24077915]
grad = [   414820.02469026  17551961.3023989  -27270828.06916204]
step = 0.1



x = [ -1124136.14161945 -47282156.97552835  73540276.98541875]
grad = [   431436.50840142  18256321.35559408 -28364927.44639608]
step = 0.1



x = [ -1169008.08590383 -49181051.18397339  76490569.26578046]
grad = [   448719.44284377  18988942.08445041 -29502922.80361706]
step = 0.1



x = [ -1215677.64242166 -51156146.9179341   79559226.79415053]
grad = [   466695.56517834  19750957.33960706 -30686575.28370072]
step = 0.1




grad = [ 7.01198298e+08  2.97361605e+10 -4.61873654e+10]
step = 0.1



x = [-1.89080133e+09 -8.01827921e+10  1.24543396e+11]
grad = [ 7.29330866e+08  3.09292014e+10 -4.80404420e+10]
step = 0.1



x = [-1.96666054e+09 -8.33998029e+10  1.29540183e+11]
grad = [ 7.58592137e+08  3.21701081e+10 -4.99678657e+10]
step = 0.1



x = [-2.04556328e+09 -8.67458830e+10  1.34737445e+11]
grad = [ 7.89027394e+08  3.34608011e+10 -5.19726192e+10]
step = 0.1



x = [-2.12763166e+09 -9.02262108e+10  1.40143225e+11]
grad = [ 8.20683739e+08  3.48032778e+10 -5.40578052e+10]
step = 0.1



x = [-2.21299267e+09 -9.38461724e+10  1.45765890e+11]
grad = [ 8.53610163e+08  3.61996158e+10 -5.62266507e+10]
step = 0.1



x = [-2.30177844e+09 -9.76113700e+10  1.51614141e+11]
grad = [ 8.87857623e+08  3.76519761e+10 -5.84825121e+10]
step = 0.1



x = [-2.39412635e+09 -1.01527631e+11  1.57697029e+11]
grad = [ 9.23479119e+08  3.91626063e+10 -6.08288805e+10]
step = 0.1



x = [-2.49017933e+09 -1.05601015e+11  1.64023968e+11]


grad = [ 3.05273744e+12  1.29460062e+14 -2.01082282e+14]
step = 0.1



x = [-8.23164918e+12 -3.49086619e+14  5.42214588e+14]
grad = [ 3.17521588e+12  1.34654111e+14 -2.09149876e+14]
step = 0.1



x = [-8.56191001e+12 -3.63092274e+14  5.63968703e+14]
grad = [ 3.30260827e+12  1.40056550e+14 -2.17541149e+14]
step = 0.1



x = [-8.90542118e+12 -3.77659847e+14  5.86595611e+14]
grad = [ 3.43511175e+12  1.45675739e+14 -2.26269086e+14]
step = 0.1



x = [-9.26271432e+12 -3.92811885e+14  6.10130331e+14]
grad = [ 3.57293138e+12  1.51520374e+14 -2.35347197e+14]
step = 0.1



x = [-9.63434236e+12 -4.08571835e+14  6.34609284e+14]
grad = [ 3.71628046e+12  1.57599502e+14 -2.44789528e+14]
step = 0.1



x = [-1.00208804e+13 -4.24964088e+14  6.60070353e+14]
grad = [ 3.86538082e+12  1.63922529e+14 -2.54610694e+14]
step = 0.1



x = [-1.04229268e+13 -4.42014012e+14  6.86552943e+14]
grad = [ 4.02046322e+12  1.70499242e+14 -2.64825894e+14]
step = 0.1



x = [-1.08411035e+13 -4.59747994e+14  7.14098036e+14]


x = [-9.96589814e+16 -4.22632417e+18  6.56448711e+18]
grad = [ 3.84417242e+16  1.63023127e+18 -2.53213708e+18]
step = 0.1



x = [-1.03657385e+17 -4.39588792e+18  6.82785997e+18]
grad = [ 3.99840392e+16  1.69563755e+18 -2.63372860e+18]
step = 0.1



x = [-1.07816209e+17 -4.57225472e+18  7.10179957e+18]
grad = [ 4.15882331e+16  1.76366798e+18 -2.73939605e+18]
step = 0.1



x = [-1.12141888e+17 -4.75569750e+18  7.38672987e+18]
grad = [ 4.32567888e+16  1.83442786e+18 -2.84930297e+18]
step = 0.1



x = [-1.16641116e+17 -4.94650017e+18  7.68309182e+18]
grad = [ 4.49922883e+16  1.90802668e+18 -2.96361946e+18]
step = 0.1



x = [-1.21320858e+17 -5.14495801e+18  7.99134406e+18]
grad = [ 4.67974175e+16  1.98457835e+18 -3.08252241e+18]
step = 0.1



x = [-1.26188355e+17 -5.35137814e+18  8.31196364e+18]
grad = [ 4.86749701e+16  2.06420133e+18 -3.20619586e+18]
step = 0.1



x = [-1.31251140e+17 -5.56608003e+18  8.64544676e+18]
grad = [ 5.06278517e+16  2.14701886e+18 -3.33483119e+18]
step = 0.1





In [72]:
a = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1],
])
b = np.array([1, 1, 1])

In [73]:
a @ b

array([3, 3, 3])

In [75]:
b

array([1, 1, 1])

In [51]:
b = b.reshape(3, 1)

In [53]:
np.linalg.norm(a @ b)

5.196152422706632

In [200]:
a = np.array([1, 2])
b = np.array([3, 4])
a - 3 * b

array([ -8, -10])

In [202]:
A = np.array([
            [1/17*100, 1/51*100, 1/51*100],
            [1/17*100, -5/51*100, 10/51*100],
            [-4/17*100, 1/51*100, -20/51*100]
    ])
b = np.array([2000, 10000, 100000])

In [204]:
A = np.array([
    [1, -1],
    [3, 2]
])
b = np.array([7, 16])

In [199]:
def solveee(A, b, max_n_iters, tol):
    n = A.shape[0]
    x = np.zeros(n)
    it = 0
    step = 0.1
    
    while it < max_n_iters and np.linalg.norm(A @ x - b) > tol:
        grad = 2 * A @ x - b
        x -= step * grad
#         print(x)
        it+=1
        
#         print(f'x =        {x}')
#         print(f'grad =     {grad}')
#         print()
#         print()
#         print()
        
    return x

In [195]:
A = np.array([
    [2, 1],
    [5, -3]
])
b = np.array([-1, -19])

In [205]:
np.linalg.solve(A, b)

array([ 6., -1.])

In [206]:
b

array([ 7, 16])

In [207]:
x = solveee(A, b, 100, 0.01)
x

array([ 3. , -0.5])